Repository edwinvautier/go-bot, pull requests merged in 2020-11, with the labels that each got.

#4 feat wit implementation
  .env.dist
  .gitignore
  README.md
  apis/wit/wit_handler.go
  assets/build.png
  commands/commandInterface.go
  commands/wit_ai.go
  discord/bot_init.go
  go.mod
  go.sum
  handlers/messages_handler.go
  main.go
Labels: enhancement

#5 feat refacto
  apis/wit/wit_handler.go
  commands/commandInterface.go
  commands/dispatcher.go
  commands/wit_ai.go
  handlers/messages_handler.go
Labels: enhancement

#6 feat unit test
  README.md
  commands/dispatcher.go
  commands/dispatcher_test.go
  handlers/messages_handler.go
Labels: documentation, enhancement

#9 feat refacto
  apis/wit/wit_handler.go
  commands/command_builder.go
  commands/wit_command.go
  commands/youtube_query.go
  connectors/discord.go
  handlers/messages_handler.go
  test/command_builder_test.go
Labels: bug

#10 Feat: Add google search by default if no results or error or not enough confidence.
  README.md
  apis/google/google_handler.go
  commands/command_builder.go
  commands/command_google.go
  commands/youtube_query.go
  go.mod
  go.sum
  handlers/messages_handler.go
  test/command_builder_test.go
Labels: documentation, enhancement

#11 Refacto: Added generic command.
  apis/wit/wit_handler.go
  commands/command_builder.go
  commands/wit_command.go
  commands/youtube_query.go
  connectors/discord.go
  handlers/messages_handler.go
  main.go
  test/command_builder_test.go
Labels: enhancement

#12 Feat: Add tests for google cmd.
  commands/command_google.go
  connectors/discord.go
  test/command_google_test.go
Labels: enhancement
